<a href="https://colab.research.google.com/github/xhxuciedu/CS284A/blob/master/pytorch-tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import matplotlib.pylab as plt
import sys
import torch 
import torchvision
import torch.nn as nn
import torchvision.transforms as transforms

In [15]:
from IPython.display import HTML, display
def set_default(figsize=(8, 5), dpi=100):
    plt.style.use(['dark_background', 'bmh'])
    plt.rc('axes', facecolor='k')
    plt.rc('figure', facecolor='k')
    plt.rc('figure', figsize=figsize, dpi=dpi)

set_default()

### Check Package Versions

In [16]:
print('__Python VERSION:', sys.version)
print('__PyTorch VERSION:', torch.__version__)
print('__CUDNN VERSION:', torch.backends.cudnn.version())
print('__Number CUDA Devices:', torch.cuda.device_count())

__Python VERSION: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
__PyTorch VERSION: 1.7.0+cu101
__CUDNN VERSION: 7603
__Number CUDA Devices: 1


### PyTorch
What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of audiences:

* A replacement for numpy to use the power of GPUs
* a deep learning research platform that provides maximum flexibility and speed





### Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.


Construct a 5x3 matrix, uninitialized

In [17]:
x = torch.Tensor(5, 3)
print(x)

tensor([[5.8067e-36, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 0.0000e+00, 0.0000e+00]])


In [18]:
# get its size
y = torch.rand(5, 3)
print(x + y)

tensor([[6.7897e-01, 2.4498e-01, 3.4984e-01],
        [9.6603e-01,        nan, 9.7634e-01],
        [3.4864e-01, 6.4157e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [6.7610e-01, 6.2939e-01, 9.4387e-01]])


In [19]:
# Addition: in-place
y.add_(x)

tensor([[6.7897e-01, 2.4498e-01, 3.4984e-01],
        [9.6603e-01,        nan, 9.7634e-01],
        [3.4864e-01, 6.4157e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [6.7610e-01, 6.2939e-01, 9.4387e-01]])

### Create tensors

In [20]:
# random
v = torch.rand(2, 3)            # Initialize with random number (uniform distribution)
v = torch.randn(2, 3)           # With normal distribution (SD=1, mean=0)
v = torch.randperm(4)   

# ones
eye = torch.eye(3)              # Create an identity 3x3 tensor
v = torch.ones(10)              # A tensor of size 10 containing all ones
v = torch.ones(2, 1, 2, 1)      # Size 2x1x2x1
v = torch.ones_like(eye)        # A tensor with same shape as eye. Fill it with 1.

# zeros
v = torch.zeros(10) 

# range of values
v = torch.arange(5)             # similar to range(5) but creating a Tensor
v = torch.arange(0, 5, step=1)  # Size 5. Similar to range(0, 5, 1)

# linear or log scale
v = torch.linspace(1, 10, steps=10) # Create a Tensor with 10 linear points for (1, 10) inclusively
v = torch.logspace(start=-10, end=10, steps=5) # Size 5: 1.0e-10 1.0e-05 1.0e+00, 1.0e+05, 1.0e+10

### Dot product, component-wide product, matrix multiplication, 

In [21]:
# Dot product of 2 tensors
r = torch.dot(torch.Tensor([4, 2]), torch.Tensor([3, 1])) # 14

In [22]:
# component-wise product
torch.Tensor([4, 2])* torch.Tensor([3, 1])

tensor([12.,  2.])

In [23]:
# Matrix x Matrix
# Size 2x4
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 4)
r = torch.mm(mat1, mat2)

In [24]:
# Batch Matrix x Matrix
# Size 10x3x5
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
r = torch.bmm(batch1, batch2)

###Squeeze and unsqueeze

In [25]:
t = torch.ones(2,1,2,1) # Size 2x1x2x1
r = torch.squeeze(t)     # Size 2x2
r = torch.squeeze(t, 1)  # Squeeze dimension 1: Size 2x2x1

# Un-squeeze a dimension
x = torch.Tensor([1, 2, 3])
r = torch.unsqueeze(x, 0)       # Size: 1x3
r = torch.unsqueeze(x, 1)       # Size: 3x1

### Transpose


In [26]:
# Transpose dim 0 and 1
v = torch.randn(3,2)
r = torch.transpose(v, 0, 1)
print(r.shape)

torch.Size([2, 3])


### Numpy Bridge
Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

Converting torch Tensor to numpy Array

In [27]:
# Create a numpy array.
x = np.array([[1, 2], [3, 4]])

# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)

# Convert the torch tensor to a numpy array.
z = y.numpy()

In [28]:
# Conversion
a = np.array([1, 2, 3])
v = torch.from_numpy(a)         # Convert a numpy array to a Tensor

b = v.numpy()                   # Tensor to numpy
b[1] = -1                       # Numpy and Tensor share the same memory
assert(a[1] == b[1])            # Change Numpy will also change the Tensor

### Reshape tensor

In [29]:
### Tensor resizing
x = torch.randn(2, 3)            # Size 2x3
y = x.view(6)                    # Resize x to size 6
z = x.view(-1, 2)                # Size 3x2
print(y.shape, z.shape)

torch.Size([6]) torch.Size([3, 2])


###CUDA Tensors

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.


Tensors can be moved onto GPU using the .cuda function.

In [30]:
# let us run this cell only if CUDA is available

x = torch.rand(3,2)
y = torch.rand(3,2)
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [31]:
x

tensor([[0.8200, 0.7632],
        [0.2346, 0.3053],
        [0.6123, 0.0609]], device='cuda:0')

In [32]:
y

tensor([[0.2591, 0.3079],
        [0.3886, 0.8800],
        [0.2207, 0.0953]], device='cuda:0')

## Autograd: automatic differentiation

Central to all neural networks in PyTorch is autograd, a core torch package for automatic differentiation. 


The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

Let us see this in more simple terms with some examples.

In [33]:
# create an variable
x = torch.ones((2,2), requires_grad=True)

# Do an operation of variable:
y = x + 2

# Do more operations on y
z = y * y * 3
out = z.mean()

In [34]:
# Gradients
# ---------
# let's backprop now
# ``out.backward()`` is equivalent to doing ``out.backward(torch.Tensor([1.0]))``
out.backward()

In [35]:
###############################################################
# print gradients d(out)/dx
#

print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have got a matrix of ``4.5``. Let’s call the ``out`` *Variable* $o$.
We have that: $o = \frac{1}{4}\sum_i z_i$, 
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$

Therefore,
$$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$$ hence
$$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$$

In [36]:
# You can do many crazy things with autograd!
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  786.5998, -1256.1101,  -949.4398], grad_fn=<MulBackward0>)


In [37]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


### Basic autograd example 1 

In [38]:
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [39]:
# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

In [40]:
# Compute gradients.
y.backward()

In [41]:
# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


In [42]:
y.detach().numpy()

array(5., dtype=float32)

### Basic autograd example 2  

In [43]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)
print(x.shape, y.shape)

torch.Size([10, 3]) torch.Size([10, 2])


In [44]:
# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 1.3139e-04,  3.5169e-01,  1.7677e-01],
        [-2.7495e-01,  3.2226e-01,  1.1678e-01]], requires_grad=True)
b:  Parameter containing:
tensor([-0.3082,  0.0621], requires_grad=True)


In [45]:
loss = torch.sum((linear(x)-y)**2)/y.shape[0]
print('loss: ', loss.data.numpy())

loss:  3.1104836


In [46]:
loss.backward()

In [47]:
print('w grad: ', linear.weight.grad)
print('b grad: ', linear.bias.grad)

w grad:  tensor([[ 0.6055,  0.2772, -0.3877],
        [-0.3933,  1.1693,  1.8184]])
b grad:  tensor([-0.1714,  0.3147])


In [48]:
# check grad
print('w grad:', (linear(x)-y).transpose(0,1).mm(x)/y.shape[0]*2)
print('b grad:', 2*torch.mean(linear(x)-y, dim=0))

w grad: tensor([[ 0.6055,  0.2772, -0.3877],
        [-0.3933,  1.1693,  1.8184]], grad_fn=<MulBackward0>)
b grad: tensor([-0.1714,  0.3147], grad_fn=<MulBackward0>)


###. Basic autograd example 3

In [49]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)
linear = nn.Linear(3, 2)

In [50]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss:  1.4289391040802002
dL/dw:  tensor([[ 0.4425,  0.4435, -0.2337],
        [ 0.6657,  0.2639, -0.1948]])
dL/db:  tensor([-0.5005, -0.2522])
loss after 1 step optimization:  1.4158974885940552


## Input pipeline, Data loader

In [51]:
# Download and construct CIFAR-10 dataset.
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

# Fetch one data pair (read data from disk).
image, label = train_dataset[0]
print (image.size())
print (label)

# Data loader (this provides queues and threads in a very simple way).
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64, 
                                           shuffle=True)

# When iteration starts, queue and thread start to load data from files.
data_iter = iter(train_loader)

# Mini-batch images and labels.
images, labels = data_iter.next()

# Actual usage of the data loader is as below.
for images, labels in train_loader:
    # Training code should be written here.
    pass

Extracting ../../data/cifar-10-python.tar.gz to ../../data/
torch.Size([3, 32, 32])
6


### Input pipeline for custom dataset

In [52]:
# # ================================================================== #
# #                  Input pipeline for custom dataset                 #
# # ================================================================== #

# # You should build your custom dataset as below.
# class CustomDataset(torch.utils.data.Dataset):
#     def __init__(self):
#         # TODO
#         # 1. Initialize file paths or a list of file names. 
#         pass
#     def __getitem__(self, index):
#         # TODO
#         # 1. Read one data from file (e.g. using numpy.fromfile, PIL.Image.open).
#         # 2. Preprocess the data (e.g. torchvision.Transform).
#         # 3. Return a data pair (e.g. image and label).
#         pass
#     def __len__(self):
#         # You should change 0 to the total size of your dataset.
#         return 0 

# # You can then use the prebuilt data loader. 
# custom_dataset = CustomDataset()
# train_loader = torch.utils.data.DataLoader(dataset=custom_dataset,
#                                            batch_size=64, 
#                                            shuffle=True)


### Pretrained model

In [53]:
# ================================================================== #
#                           Pretrained model                         #
# ================================================================== #

# Download and load the pretrained ResNet-18.
resnet = torchvision.models.resnet18(pretrained=True)

# If you want to finetune only the top layer of the model, set as below.
for param in resnet.parameters():
    param.requires_grad = False

# Replace the top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)  # 100 is an example.

# Forward pass.
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print (outputs.size())     # (64, 100)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth



torch.Size([64, 100])


### Save and load the model    

In [54]:
# Save and load the entire model.
torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt')

# Save and load only the model parameters (recommended).
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

<All keys matched successfully>