## Tutorial 1:  Introduction

##### NumPy

In [1]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [2]:
5*x

array([[ 5, 10, 15],
       [20, 25, 30]])

##### matplotlib

In [3]:
#%matplotlib inline
import matplotlib.pyplot as plt

# Generate a sequence numbers from -10 to 10 with 100 steps in between
x = np.linspace(-10, 10, 100)
# create a second array using sinus
y = np.exp(x)
# The plot function makes a line chart of one array against another
plt.plot(x, y, marker='o')

In [4]:
y

array([4.53999298e-05, 5.55637361e-05, 6.80029415e-05, 8.32269459e-05,
       1.01859190e-04, 1.24662685e-04, 1.52571261e-04, 1.86727806e-04,
       2.28531070e-04, 2.79692945e-04, 3.42308569e-04, 4.18942123e-04,
       5.12731841e-04, 6.27518520e-04, 7.68002806e-04, 9.39937692e-04,
       1.15036411e-03, 1.40789927e-03, 1.72308953e-03, 2.10884229e-03,
       2.58095457e-03, 3.15875992e-03, 3.86592014e-03, 4.73139424e-03,
       5.79062440e-03, 7.08698731e-03, 8.67357053e-03, 1.06153465e-02,
       1.29918331e-02, 1.59003503e-02, 1.94600051e-02, 2.38165696e-02,
       2.91484502e-02, 3.56739933e-02, 4.36604277e-02, 5.34348070e-02,
       6.53974032e-02, 8.00380986e-02, 9.79564464e-02, 1.19886224e-01,
       1.46725480e-01, 1.79573314e-01, 2.19774883e-01, 2.68976487e-01,
       3.29192988e-01, 4.02890322e-01, 4.93086479e-01, 6.03475096e-01,
       7.38576715e-01, 9.03923902e-01, 1.10628782e+00, 1.35395549e+00,
       1.65706921e+00, 2.02804182e+00, 2.48206508e+00, 3.03773178e+00,
      

##### pandas

In [5]:
import pandas as pd
from IPython.display import display

# create a simple dataset of people
data = {'Name': ["John", "Anna", "Peter", "Linda"],
        'Location' : ["New York", "Paris", "Berlin", "London"],
        'Age' : [24, 13, 53, 33]
       }

data_pandas = pd.DataFrame(data)
# IPython.display allows "pretty printing" of dataframes
# in the Jupyter notebook
display(data_pandas)

Name  Location  Age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33

In [6]:
# One of many possible ways to query the table:
# selecting all rows that have an age column greate than 30
display(data_pandas[data_pandas.Age > 30])

Name Location  Age
2  Peter   Berlin   53
3  Linda   London   33

#### Versions 

In [7]:
import sys
print("Python version: {}".format(sys.version))

import pandas as pd
print("pandas version: {}".format(pd.__version__))

import matplotlib
print("matplotlib version: {}".format(matplotlib.__version__))

import numpy as np
print("NumPy version: {}".format(np.__version__))

import IPython
print("IPython version: {}".format(IPython.__version__))

import sklearn
print("scikit-learn version: {}".format(sklearn.__version__))

Python version: 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
pandas version: 0.25.1
matplotlib version: 3.1.1
NumPy version: 1.17.2
IPython version: 7.8.0
scikit-learn version: 0.21.3


### A First Application: Classifying iris species
<img src="https://github.com/xhxuciedu/SysBioShortCourse/blob/master/images/iris_petal_sepal.png?raw=1" width="300" height="300" />
#### Meet the data

In [8]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [9]:
print("Keys of iris_dataset: {}".format(iris_dataset.keys()))

Keys of iris_dataset: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [10]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [11]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [12]:
print("Feature names: {}".format(iris_dataset['feature_names']))

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [14]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [15]:
print("First five rows of data:\n{}".format(iris_dataset['data'][:5]))

First five rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [16]:
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


In [17]:
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


In [18]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#### Measuring Success: Training and testing data

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

In [20]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

X_train shape: (112, 4)
y_train shape: (112,)


In [21]:
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_test shape: (38, 4)
y_test shape: (38,)


#### First things first: Look at your data

In [23]:
# create dataframe from data in X_train
# label the columns using the strings in iris_dataset.feature_names
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
# create a scatter matrix from the dataframe, color by y_train
#pd.tools.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15), marker='o',
#                           hist_kwds={'bins': 20}, s=60, alpha=.8, cmap='hot')

#### Building your first model: k nearest neighbors

In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [25]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

#### Making predictions

In [26]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [27]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
       iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


#### Evaluating the model

In [28]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [29]:
print("Test set score: {:.2f}".format(np.mean(y_pred == y_test)))

Test set score: 0.97


In [30]:
print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))

Test set score: 0.97


### Summary and Outlook

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

print("Train set score: {:.2f}".format(knn.score(X_train, y_train)))
print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))

Train set score: 1.00
Test set score: 0.97


### Exercise 1

#### 1. Calculate the score on testing data

#### 2. Rerun the predictor with difference choices of n_neighbors.  Compare test scores. Which number is the best?